// BRSR export — generates a Word (.docx) document from saved answers.
//
// SEBI does not publish an official BRSR Excel template (the reporting format
// is a Word/PDF Annexure embedded in the LODR amendment), and listed entities
// embed the BRSR into their Annual Report. So we emit a Word document directly:
// one section heading per Section / Principle, each disclosure rendered as a
// labelled question followed by either a key/value list (FieldsQuestion) or a
// bordered table (TableQuestion) — matching the styling used by the qualitative
// MMD exporter so both outputs look consistent.

import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";
import { sections } from "@/lib/reporting/brsrSections";
import { BRSR_ANSWERS_KEY, readAnswers, type SavedAnswer } from "@/lib/reporting/storage";
import type { Field, FieldsQuestion, Section, TableQuestion } from "@/lib/reporting/frameworkTypes";

// ---------- style constants (mirrored from qualitative/exportDocx.ts) ----------

const FONT = "Calibri";
const BODY_SIZE = 22; // 11pt (docx uses half-points)
const SMALL_SIZE = 20; // 10pt
const HEADING_SIZES = { 1: 32, 2: 28, 3: 24 } as const;

const BORDER_GREY = "BFBFBF";
const HEADER_FILL = "EDE9FE"; // soft violet — BRSR brand swatch
const ROW_LABEL_FILL = "F8F8F8";

// ---------- public entrypoint ----------

export async function exportBrsrFilled(): Promise<void> {
  const answers = readAnswers(BRSR_ANSWERS_KEY);

  const children: (Paragraph | Table)[] = [];

  // Title
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: "Business Responsibility & Sustainability Report",
          bold: true,
          size: 36, // 18pt
          font: FONT,
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
      children: [
        new TextRun({
          text: "SEBI Annexure I — generated by LatSpace",
          italics: true,
          size: SMALL_SIZE,
          font: FONT,
          color: "64748B",
        }),
      ],
    }),
  );

  // Group sections under three top-level headings: Section A, Section B, Section C
  const groups = groupSections(sections);
  for (const g of groups) {
    children.push(headingParagraph(g.title, 1));
    for (const s of g.sections) {
      children.push(headingParagraph(s.title, 2));
      for (const q of s.questions) {
        const a = answers[q.id];
        children.push(headingParagraph(q.label, 3));
        if (q.description) children.push(bodyParagraph(q.description, { italic: true }));
        if (q.kind === "fields") {
          children.push(...fieldsBlock(q, a));
        } else {
          children.push(tableBlock(q, a));
        }
        // spacer
        children.push(new Paragraph({ spacing: { after: 120 }, children: [] }));
      }
    }
  }

  const doc = new Document({
    creator: "LatSpace BRSR",
    title: "Business Responsibility & Sustainability Report",
    sections: [
      {
        properties: {},
        children,
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const ts = new Date().toISOString().slice(0, 10);
  a.download = `BRSR-${ts}.docx`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ---------- section grouping ----------

interface SheetGroup {
  title: string;
  sections: Section[];
}

function groupSections(all: Section[]): SheetGroup[] {
  const a: Section[] = [];
  const b: Section[] = [];
  const c: Section[] = [];
  for (const s of all) {
    if (s.id.startsWith("A.")) a.push(s);
    else if (s.id === "B") b.push(s);
    else if (s.id.startsWith("C.")) c.push(s);
  }
  const groups: SheetGroup[] = [];
  if (a.length) groups.push({ title: "Section A — General Disclosures", sections: a });
  if (b.length) groups.push({ title: "Section B — Management & Process Disclosures", sections: b });
  if (c.length) groups.push({ title: "Section C — Principle-wise Performance Disclosure", sections: c });
  return groups;
}

// ---------- paragraph builders ----------

function headingParagraph(text: string, level: 1 | 2 | 3): Paragraph {
  return new Paragraph({
    heading:
      level === 1 ? HeadingLevel.HEADING_1 : level === 2 ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_3,
    spacing: { before: level === 1 ? 240 : 160, after: 200 },
    children: [new TextRun({ text, bold: true, size: HEADING_SIZES[level], font: FONT })],
  });
}

function bodyParagraph(
  text: string,
  opts: { italic?: boolean; bold?: boolean; small?: boolean } = {},
): Paragraph {
  return new Paragraph({
    spacing: { after: 120 },
    children: [
      new TextRun({
        text,
        size: opts.small ? SMALL_SIZE : BODY_SIZE,
        font: FONT,
        italics: opts.italic,
        bold: opts.bold,
        color: opts.italic ? "64748B" : undefined,
      }),
    ],
  });
}

// ---------- FieldsQuestion -> two-column table (label | value) ----------

function fieldsBlock(q: FieldsQuestion, a: SavedAnswer | undefined): (Paragraph | Table)[] {
  const values = a?.values ?? {};
  const rows: TableRow[] = q.fields.map(
    (f) =>
      new TableRow({
        children: [
          new TableCell({
            width: { size: 40, type: WidthType.PERCENTAGE },
            shading: { type: ShadingType.CLEAR, color: "auto", fill: ROW_LABEL_FILL },
            children: [bodyParagraph(labelText(f), { bold: true, small: true })],
          }),
          new TableCell({
            width: { size: 60, type: WidthType.PERCENTAGE },
            children: [bodyParagraph(formatValue(values[f.id]) || "—")],
          }),
        ],
      }),
  );
  return [
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: tableBorders(),
      rows,
    }),
  ];
}

// ---------- TableQuestion -> bordered table ----------

function tableBlock(q: TableQuestion, a: SavedAnswer | undefined): Table {
  const rowsData = (a?.rows ?? []) as Record<string, unknown>[];
  const rowCount = Math.max(rowsData.length, q.minRows);

  const headerCells: TableCell[] = [];
  if (q.rowLabel) headerCells.push(headerCell(""));
  for (const c of q.columns) headerCells.push(headerCell(labelText(c)));
  const headerRow = new TableRow({ tableHeader: true, children: headerCells });

  const bodyRows: TableRow[] = [];
  for (let r = 0; r < rowCount; r++) {
    const rowData = rowsData[r] ?? {};
    const cells: TableCell[] = [];
    if (q.rowLabel) {
      cells.push(
        new TableCell({
          shading: { type: ShadingType.CLEAR, color: "auto", fill: ROW_LABEL_FILL },
          children: [bodyParagraph(q.rowLabel(r), { bold: true, small: true })],
        }),
      );
    }
    for (const c of q.columns) {
      cells.push(
        new TableCell({
          children: [bodyParagraph(formatValue(rowData[c.id]) || "—", { small: true })],
        }),
      );
    }
    bodyRows.push(new TableRow({ children: cells }));
  }

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: tableBorders(),
    rows: [headerRow, ...bodyRows],
  });
}

function headerCell(text: string): TableCell {
  return new TableCell({
    shading: { type: ShadingType.CLEAR, color: "auto", fill: HEADER_FILL },
    children: [bodyParagraph(text, { bold: true, small: true })],
  });
}

function tableBorders() {
  const b = { style: BorderStyle.SINGLE, size: 4, color: BORDER_GREY };
  return {
    top: b,
    bottom: b,
    left: b,
    right: b,
    insideHorizontal: b,
    insideVertical: b,
  };
}

// ---------- value formatting ----------

function labelText(f: Field): string {
  return f.unit ? `${f.label} (${f.unit})` : f.label;
}

function formatValue(v: unknown): string {
  if (v == null || v === "") return "";
  if (typeof v === "boolean") return v ? "Yes" : "No";
  if (typeof v === "number") return String(v);
  return String(v);
}
