// CDP export — generates a Word (.docx) document from saved answers.
//
// CDP doesn't ship an offline template; filers complete the questionnaire
// inside CDP's Online Response System and most also retain a self-authored
// PDF for their records. This export produces that PDF-friendly companion
// document — one heading per Module, each numbered question rendered as a
// labelled block followed by either a key/value table (FieldsQuestion) or a
// bordered grid (TableQuestion).
//
// Styling matches the BRSR exporter (Calibri body, half-point sizing,
// bordered tables) so all framework outputs feel consistent. Brand fill is
// rose to match the on-screen CDP framework swatch.

import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";
import { sections } from "@/lib/reporting/cdpSections";
import { CDP_ANSWERS_KEY, readAnswers, type SavedAnswer } from "@/lib/reporting/storage";
import type { Field, FieldsQuestion, Section, TableQuestion } from "@/lib/reporting/frameworkTypes";

// ---------- style constants ----------

const FONT = "Calibri";
const BODY_SIZE = 22; // 11pt
const SMALL_SIZE = 20; // 10pt
const HEADING_SIZES = { 1: 32, 2: 28, 3: 24 } as const;

const BORDER_GREY = "BFBFBF";
const HEADER_FILL = "FFE4E6"; // rose 100 — matches CDP framework swatch
const ROW_LABEL_FILL = "F8F8F8";

// ---------- public entrypoint ----------

export async function exportCdpFilled(): Promise<void> {
  const answers = readAnswers(CDP_ANSWERS_KEY);

  const children: (Paragraph | Table)[] = [];

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: "CDP Climate Change Response",
          bold: true,
          size: 36,
          font: FONT,
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
      children: [
        new TextRun({
          text: "CDP 2026 questionnaire — generated by LatSpace",
          italics: true,
          size: SMALL_SIZE,
          font: FONT,
          color: "64748B",
        }),
      ],
    }),
  );

  for (const s of sections) {
    children.push(headingParagraph(s.title, 1));
    for (const q of s.questions) {
      const a = answers[q.id];
      children.push(headingParagraph(q.label, 2));
      if (q.description) children.push(bodyParagraph(q.description, { italic: true }));
      if (q.kind === "fields") {
        children.push(...fieldsBlock(q, a));
      } else {
        children.push(tableBlock(q, a));
      }
      children.push(new Paragraph({ spacing: { after: 120 }, children: [] }));
    }
  }

  const doc = new Document({
    creator: "LatSpace CDP",
    title: "CDP Climate Change Response",
    sections: [{ properties: {}, children }],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const ts = new Date().toISOString().slice(0, 10);
  a.download = `CDP-${ts}.docx`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ---------- paragraph builders ----------

function headingParagraph(text: string, level: 1 | 2 | 3): Paragraph {
  return new Paragraph({
    heading:
      level === 1 ? HeadingLevel.HEADING_1 : level === 2 ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_3,
    spacing: { before: level === 1 ? 240 : 160, after: 200 },
    children: [new TextRun({ text, bold: true, size: HEADING_SIZES[level], font: FONT })],
  });
}

function bodyParagraph(
  text: string,
  opts: { italic?: boolean; bold?: boolean; small?: boolean } = {},
): Paragraph {
  return new Paragraph({
    spacing: { after: 120 },
    children: [
      new TextRun({
        text,
        size: opts.small ? SMALL_SIZE : BODY_SIZE,
        font: FONT,
        italics: opts.italic,
        bold: opts.bold,
        color: opts.italic ? "64748B" : undefined,
      }),
    ],
  });
}

// ---------- block builders ----------

function fieldsBlock(q: FieldsQuestion, a: SavedAnswer | undefined): (Paragraph | Table)[] {
  const values = a?.values ?? {};
  const rows: TableRow[] = q.fields.map(
    (f) =>
      new TableRow({
        children: [
          new TableCell({
            width: { size: 40, type: WidthType.PERCENTAGE },
            shading: { type: ShadingType.CLEAR, color: "auto", fill: ROW_LABEL_FILL },
            children: [bodyParagraph(labelText(f), { bold: true, small: true })],
          }),
          new TableCell({
            width: { size: 60, type: WidthType.PERCENTAGE },
            children: [bodyParagraph(formatValue(values[f.id]) || "—")],
          }),
        ],
      }),
  );
  return [
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: tableBorders(),
      rows,
    }),
  ];
}

function tableBlock(q: TableQuestion, a: SavedAnswer | undefined): Table {
  const rowsData = (a?.rows ?? []) as Record<string, unknown>[];
  const rowCount = Math.max(rowsData.length, q.minRows);

  const headerCells: TableCell[] = [];
  if (q.rowLabel) headerCells.push(headerCell(""));
  for (const c of q.columns) headerCells.push(headerCell(labelText(c)));
  const headerRow = new TableRow({ tableHeader: true, children: headerCells });

  const bodyRows: TableRow[] = [];
  for (let r = 0; r < rowCount; r++) {
    const rowData = rowsData[r] ?? {};
    const cells: TableCell[] = [];
    if (q.rowLabel) {
      cells.push(
        new TableCell({
          shading: { type: ShadingType.CLEAR, color: "auto", fill: ROW_LABEL_FILL },
          children: [bodyParagraph(q.rowLabel(r), { bold: true, small: true })],
        }),
      );
    }
    for (const c of q.columns) {
      cells.push(
        new TableCell({
          children: [bodyParagraph(formatValue(rowData[c.id]) || "—", { small: true })],
        }),
      );
    }
    bodyRows.push(new TableRow({ children: cells }));
  }

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: tableBorders(),
    rows: [headerRow, ...bodyRows],
  });
}

function headerCell(text: string): TableCell {
  return new TableCell({
    shading: { type: ShadingType.CLEAR, color: "auto", fill: HEADER_FILL },
    children: [bodyParagraph(text, { bold: true, small: true })],
  });
}

function tableBorders() {
  const b = { style: BorderStyle.SINGLE, size: 4, color: BORDER_GREY };
  return {
    top: b,
    bottom: b,
    left: b,
    right: b,
    insideHorizontal: b,
    insideVertical: b,
  };
}

// ---------- value formatting ----------

function labelText(f: Field): string {
  return f.unit ? `${f.label} (${f.unit})` : f.label;
}

function formatValue(v: unknown): string {
  if (v == null || v === "") return "";
  if (typeof v === "boolean") return v ? "Yes" : "No";
  if (typeof v === "number") return String(v);
  return String(v);
}
