// Checklist export — generates a Word (.docx) document from the VSME data
// checklist shown on the Extract → Checklist tab.
//
// One heading per category (Environmental / Social / Governance / General
// Information), each data point rendered as a checkbox line: ☒ for items the
// user has ticked off, ☐ for the rest, with collected items struck through so
// the printout doubles as a progress sheet.
//
// Styling matches the other framework exporters (Calibri body, half-point
// sizing) so all Word outputs feel consistent. Brand fill is the LatSpace green
// used on the checklist UI.

import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from "docx";
import { saveAs } from "file-saver";

import {
  CHECKLIST_CATEGORIES,
  type VsmeChecklist,
} from "@/lib/types/checklist";

// ---------- style constants ----------

const FONT = "Calibri";
const BODY_SIZE = 22; // 11pt
const SMALL_SIZE = 20; // 10pt
const HEADING_SIZE = 28; // 14pt
const BRAND = "074D47"; // LatSpace green
const MUTED = "64748B"; // slate

// ---------- public entrypoint ----------

/**
 * Build and download a .docx of the checklist. `selected` is the set of ticked
 * item titles (drives the ☒/☐ marker and strike-through). `companyName` is used
 * in the title and filename when available.
 */
export async function exportChecklistDocx(
  checklist: VsmeChecklist,
  selected: ReadonlySet<string>,
  companyName?: string,
): Promise<void> {
  const children: Paragraph[] = [];

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 120 },
      children: [
        new TextRun({
          text: "VSME Data Checklist",
          bold: true,
          size: 36,
          font: FONT,
          color: BRAND,
        }),
      ],
    }),
  );

  if (companyName) {
    children.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 80 },
        children: [
          new TextRun({ text: companyName, size: BODY_SIZE, font: FONT }),
        ],
      }),
    );
  }

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 360 },
      children: [
        new TextRun({
          text: "Data points to collect to fill a VSME document — generated by LatSpace",
          italics: true,
          size: SMALL_SIZE,
          font: FONT,
          color: MUTED,
        }),
      ],
    }),
  );

  for (const { key, label } of CHECKLIST_CATEGORIES) {
    const items = checklist[key];
    const done = items.filter((it) => selected.has(it)).length;

    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 240, after: 160 },
        children: [
          new TextRun({
            text: `${label}  (${done}/${items.length})`,
            bold: true,
            size: HEADING_SIZE,
            font: FONT,
            color: BRAND,
          }),
        ],
      }),
    );

    if (items.length === 0) {
      children.push(
        new Paragraph({
          spacing: { after: 120 },
          children: [
            new TextRun({
              text: "No data points in this category.",
              italics: true,
              size: SMALL_SIZE,
              font: FONT,
              color: MUTED,
            }),
          ],
        }),
      );
      continue;
    }

    for (const item of items) {
      const isDone = selected.has(item);
      children.push(
        new Paragraph({
          spacing: { after: 60 },
          children: [
            new TextRun({
              // Unicode ballot boxes — render reliably in Word.
              text: isDone ? "☒  " : "☐  ",
              size: BODY_SIZE,
              font: FONT,
              color: isDone ? BRAND : "000000",
            }),
            new TextRun({
              text: item,
              size: BODY_SIZE,
              font: FONT,
              strike: isDone,
              color: isDone ? MUTED : "000000",
            }),
          ],
        }),
      );
    }
  }

  const doc = new Document({
    creator: "LatSpace",
    title: "VSME Data Checklist",
    sections: [{ properties: {}, children }],
  });

  const blob = await Packer.toBlob(doc);
  const ts = new Date().toISOString().slice(0, 10);
  const slug = (companyName || "VSME")
    .trim()
    .replace(/[^\w-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 40) || "VSME";
  saveAs(blob, `${slug}-Checklist-${ts}.docx`);
}
