// Shared contract for the VSME data checklist — the AI-generated list of data
// points an org needs to collect to fill a VSME document, grouped into four
// categories. Generated by lib/ai/checklist.ts (LLM, structured output) when the
// user saves their AI Context, persisted inside the org's onboarding_profile
// JSONB (alongside businessContext), and read by the Checklist tab on
// /corporate/extract.

/** The four VSME data categories. */
export type ChecklistCategory =
  | "environmental"
  | "social"
  | "governance"
  | "general";

export interface VsmeChecklist {
  /** Environmental data points to collect (titles only). */
  environmental: string[];
  /** Social data points to collect. */
  social: string[];
  /** Governance data points to collect. */
  governance: string[];
  /** General information data points to collect. */
  general: string[];
  /** ISO timestamp of when this checklist was generated, or null if never. */
  generatedAt: string | null;
}

/** Display metadata for each category (label + order) for the UI. */
export const CHECKLIST_CATEGORIES: { key: ChecklistCategory; label: string }[] = [
  { key: "environmental", label: "Environmental" },
  { key: "social", label: "Social" },
  { key: "governance", label: "Governance" },
  { key: "general", label: "General Information" },
];

/** Max number of items kept per category (guards against a runaway LLM list). */
export const MAX_CHECKLIST_ITEMS_PER_CATEGORY = 40;
/** Max characters kept per item title. */
export const MAX_CHECKLIST_ITEM_LENGTH = 200;

/** An empty checklist (used as a default before anything is generated). */
export function emptyChecklist(): VsmeChecklist {
  return {
    environmental: [],
    social: [],
    governance: [],
    general: [],
    generatedAt: null,
  };
}

/** True when every category is empty. */
export function isChecklistEmpty(checklist: VsmeChecklist | null | undefined): boolean {
  if (!checklist) return true;
  return (
    checklist.environmental.length === 0 &&
    checklist.social.length === 0 &&
    checklist.governance.length === 0 &&
    checklist.general.length === 0
  );
}

/** All item titles across every category, in display order. */
export function allChecklistItems(
  checklist: VsmeChecklist | null | undefined,
): string[] {
  if (!checklist) return [];
  return [
    ...checklist.environmental,
    ...checklist.social,
    ...checklist.governance,
    ...checklist.general,
  ];
}

/**
 * Normalize a stored selection (the set of selected item titles). Coerces to a
 * de-duplicated string array. If `validTitles` is provided, selections are
 * pruned to titles that still exist — so when the checklist is regenerated,
 * selections for items that disappeared are dropped while surviving items keep
 * their checked state. NEVER throws.
 */
export function normalizeChecklistSelection(
  stored: unknown,
  validTitles?: readonly string[],
): string[] {
  if (!Array.isArray(stored)) return [];
  const valid = validTitles ? new Set(validTitles) : null;
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of stored) {
    if (typeof item !== "string") continue;
    const title = item.trim();
    if (!title || seen.has(title)) continue;
    if (valid && !valid.has(title)) continue;
    seen.add(title);
    out.push(title);
  }
  return out;
}

/** Clean one category's array: coerce to strings, trim, drop empties, cap. */
function normalizeItems(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  const out: string[] = [];
  for (const item of value) {
    if (typeof item !== "string") continue;
    const trimmed = item.trim().slice(0, MAX_CHECKLIST_ITEM_LENGTH);
    if (trimmed) out.push(trimmed);
    if (out.length >= MAX_CHECKLIST_ITEMS_PER_CATEGORY) break;
  }
  return out;
}

/**
 * Coerce a stored (possibly legacy/partial/missing) checklist blob into the full
 * current shape. NEVER throws — mirrors normalizeStoredProfile in onboarding.ts.
 * Used both when reading from the DB and when validating the LLM's tool output.
 */
export function normalizeStoredChecklist(
  stored: Partial<VsmeChecklist> | null | undefined,
): VsmeChecklist {
  if (!stored || typeof stored !== "object") return emptyChecklist();
  return {
    environmental: normalizeItems(stored.environmental),
    social: normalizeItems(stored.social),
    governance: normalizeItems(stored.governance),
    general: normalizeItems(stored.general),
    generatedAt:
      typeof stored.generatedAt === "string" ? stored.generatedAt : null,
  };
}
