// Shared contract for the onboarding profile captured when a user creates their
// organization, and edited later from the "AI Context" page.
//
// Persisted as the `onboarding_profile` JSONB column on organizations
// (migration 0006). Written by /api/onboarding (POST, at org creation) and
// /api/ai-context (PATCH, edits). Read by the AI Context page and, later, by the
// agent routes to ground the assistant in the org's reporting situation.

import {
  normalizeStoredChecklist,
  normalizeChecklistSelection,
  allChecklistItems,
  type VsmeChecklist,
} from "@/lib/types/checklist";

/** Report types the org intends to produce. */
export type ReportType = "vsme" | "cdp_sme";

/** VSME module scope. */
export type VsmeModules = "basic" | "basic_comprehensive";

export interface VsmeContext {
  /** Why the org is doing VSME (free text — e.g. bank request, customer ask). */
  purpose: string;
  /** Basic module only, or Basic + Comprehensive. */
  modules: VsmeModules;
}

export interface OnboardingProfile {
  /** Company name (mirrors organizations.name; kept here so the profile is self-contained). */
  companyName: string;
  /** Public website URL. */
  websiteUrl: string;
  /** Which reports the org is producing. */
  reports: ReportType[];
  /** VSME-specific answers. Present/meaningful only when reports includes "vsme". */
  vsme: VsmeContext | null;
  /** Reporting year, e.g. 2025. */
  reportingYear: number | null;
  /**
   * Free-text business context describing what the company does, its sector,
   * operations, and sustainability-relevant footprint. Authored by the user or
   * auto-generated by Sculptor (LLM research of the company's website/domain).
   * Grounds the AI assistant in company-specific knowledge.
   */
  businessContext: string;
  /**
   * AI-generated VSME data checklist — the data points the org needs to collect,
   * grouped into four categories. Owned by the server (regenerated by
   * lib/ai/checklist.ts on save); the client never sends it. Optional because
   * older stored profiles predate it.
   */
  checklist?: VsmeChecklist;
  /**
   * The checklist items the user has ticked off, stored as item titles (not
   * indices) so selections survive checklist regeneration: surviving items keep
   * their checked state, removed items are pruned. Server-owned via
   * /api/ai-context/checklist-selection. Optional — older profiles predate it.
   */
  checklistSelected?: string[];
  /** ISO timestamp of the last edit. */
  updatedAt: string | null;
}

/** Max length of the businessContext narrative (DB-friendly, generous cap). */
export const BUSINESS_CONTEXT_MAX = 8000;

export const REPORT_OPTIONS: { value: ReportType; label: string; description: string }[] = [
  {
    value: "vsme",
    label: "VSME",
    description: "EFRAG Voluntary Sustainability Reporting Standard for non-listed SMEs.",
  },
  {
    value: "cdp_sme",
    label: "CDP SME",
    description: "CDP climate disclosure questionnaire for small and mid-sized enterprises.",
  },
];

export const VSME_MODULE_OPTIONS: { value: VsmeModules; label: string; description: string }[] = [
  {
    value: "basic",
    label: "Basic Module only",
    description: "Disclosures B1–B11.",
  },
  {
    value: "basic_comprehensive",
    label: "Basic + Comprehensive Module",
    description: "Disclosures B1–B11 plus C1–C9.",
  },
];

/** An empty profile seeded with a company name (used as a wizard / editor default). */
export function emptyOnboardingProfile(companyName = ""): OnboardingProfile {
  return {
    companyName,
    websiteUrl: "",
    reports: [],
    vsme: null,
    reportingYear: null,
    businessContext: "",
    updatedAt: null,
  };
}

/**
 * Coerce a stored (possibly legacy/partial) profile blob into the full current
 * shape, filling defaults for any missing field. Unlike parseOnboardingProfile,
 * this NEVER throws — it's for reading data the app itself wrote, where an older
 * blob may simply lack newer keys (e.g. businessContext). `fallbackName` is used
 * when the stored profile has no company name (mirrors organizations.name).
 */
export function normalizeStoredProfile(
  stored: Partial<OnboardingProfile> | null | undefined,
  fallbackName = "",
): OnboardingProfile {
  const base = emptyOnboardingProfile(fallbackName);
  if (!stored || typeof stored !== "object") return base;

  const reports = Array.isArray(stored.reports)
    ? stored.reports.filter(
        (r): r is ReportType => r === "vsme" || r === "cdp_sme",
      )
    : base.reports;

  const vsme: VsmeContext | null = reports.includes("vsme")
    ? {
        purpose:
          typeof stored.vsme?.purpose === "string" ? stored.vsme.purpose : "",
        modules:
          stored.vsme?.modules === "basic_comprehensive"
            ? "basic_comprehensive"
            : "basic",
      }
    : null;

  const checklist = stored.checklist
    ? normalizeStoredChecklist(stored.checklist)
    : undefined;

  return {
    companyName:
      typeof stored.companyName === "string" && stored.companyName.trim()
        ? stored.companyName
        : fallbackName,
    websiteUrl: typeof stored.websiteUrl === "string" ? stored.websiteUrl : "",
    reports,
    vsme,
    reportingYear:
      typeof stored.reportingYear === "number" ? stored.reportingYear : null,
    businessContext:
      typeof stored.businessContext === "string" ? stored.businessContext : "",
    checklist,
    // Prune selections to titles that still exist in the (normalized) checklist.
    checklistSelected: normalizeChecklistSelection(
      stored.checklistSelected,
      allChecklistItems(checklist),
    ),
    updatedAt: typeof stored.updatedAt === "string" ? stored.updatedAt : null,
  };
}

/**
 * Validate and normalize an unknown value into an OnboardingProfile. Returns
 * `{ profile }` on success or `{ error }` with a human-readable message.
 * Used by the API routes so the client and server share one validation path.
 */
export function parseOnboardingProfile(
  input: unknown,
): { profile: OnboardingProfile } | { error: string } {
  if (typeof input !== "object" || input === null) {
    return { error: "Profile must be an object." };
  }
  const raw = input as Record<string, unknown>;

  const companyName = typeof raw.companyName === "string" ? raw.companyName.trim() : "";
  if (!companyName) return { error: "Company name is required." };
  if (companyName.length > 120) {
    return { error: "Company name must be 120 characters or fewer." };
  }

  const websiteUrl = typeof raw.websiteUrl === "string" ? raw.websiteUrl.trim() : "";
  if (websiteUrl.length > 300) {
    return { error: "Website URL must be 300 characters or fewer." };
  }

  const reportsRaw = Array.isArray(raw.reports) ? raw.reports : [];
  const reports = reportsRaw.filter(
    (r): r is ReportType => r === "vsme" || r === "cdp_sme",
  );
  if (reports.length === 0) {
    return { error: "Select at least one report." };
  }

  let vsme: VsmeContext | null = null;
  if (reports.includes("vsme")) {
    const v =
      typeof raw.vsme === "object" && raw.vsme !== null
        ? (raw.vsme as Record<string, unknown>)
        : {};
    const modules = v.modules === "basic_comprehensive" ? "basic_comprehensive" : "basic";
    const purpose = typeof v.purpose === "string" ? v.purpose.trim() : "";
    if (purpose.length > 1000) {
      return { error: "VSME purpose must be 1000 characters or fewer." };
    }
    vsme = { purpose, modules };
  }

  let reportingYear: number | null = null;
  if (raw.reportingYear !== null && raw.reportingYear !== undefined && raw.reportingYear !== "") {
    const year = Number(raw.reportingYear);
    if (!Number.isInteger(year) || year < 2000 || year > 2100) {
      return { error: "Reporting year must be a year between 2000 and 2100." };
    }
    reportingYear = year;
  }

  const businessContext =
    typeof raw.businessContext === "string" ? raw.businessContext.trim() : "";
  if (businessContext.length > BUSINESS_CONTEXT_MAX) {
    return {
      error: `Business context must be ${BUSINESS_CONTEXT_MAX} characters or fewer.`,
    };
  }

  return {
    profile: {
      companyName,
      websiteUrl,
      reports,
      vsme,
      reportingYear,
      businessContext,
      updatedAt: typeof raw.updatedAt === "string" ? raw.updatedAt : null,
    },
  };
}
